[project]
    name            = "asbar-parser"
    version         = "26.8.1"
    description     = "Parses Android SMS Backup and Restore .xml files to extract media and format the text messages."
    readme          = "README.md"
    requires-python = ">=3.14"
    dependencies    = [
        "arrow>=1.3.0",
        "just-heic>=0.0.0",
        "lxml>=5.3.1",
        "playwright>=1.52.0",
    ]

    [project.scripts]
        asbar = "asbar.main:start"

[build-system]
    requires      = ["uv_build>=0.12.1,<0.13"]
    build-backend = "uv_build"

[tool.uv.build-backend]
    module-name = "asbar"
